ssh_port: 22

users:
  - name: Brue Wayne
    username: bwayne
    email: bwayne@we.com

admin_password: LearnAnsible{{ lookup('pipe', 'date +%m%y')}}
admin_password_hash: "{{ admin_password | password_hash(salt='sRvXWmR5BBwqRlih') }}"
