# --- Lookup tables --- #
# Region specific AMIs, subnets, and VPCs
ec2_regions:
  us-east-1:
    vpc: vpc-06c9a463
    subnet_id: subnet-a2169ed5
    key_name: "{{ ec2_key_name | default('training') }}"
    amis:
      centos7: ami-61bbf104
      centos7-tower: ami-877b9e91
      rhel7: ami-85241def
      rhel7-tower: ami-85241def
      ubuntu14: ami-feed08e8
      ubuntu16: ami-9dcfdb8a

  us-west-1:
    vpc: vpc-ce1f9aab
    subnet_id: subnet-25b9157c
    key_name: "{{ ec2_key_name | default('training') }}"
    amis:
      centos7: ami-af4333cf
      centos7-tower: ami-c04a00a0
      rhel7: ami-f88fc498
      rhel7-tower: ami-f88fc498
      ubuntu14: ami-6ebcec0e
      ubuntu16: ami-b05203d0

# Instance types used for lab configurations
ec2_instance_types:
  centos7:
    ami_id: "{{ ec2_regions[ec2_region].amis.centos7 }}"
    size: t2.micro
    os_type: linux
    disk_space: 10

  centos7-tower:
    ami_id: "{{ ec2_regions[ec2_region].amis['centos7-tower'] }}"
    size: t2.medium
    os_type: linux
    disk_space: 20

  # Look for owner 309956199498 to find official Red Hat AMIs
  rhel7:
    ami_id: "{{ ec2_regions[ec2_region].amis.rhel7 }}"
    size: t2.micro
    os_type: linux
    disk_space: 10

  rhel7-tower:
    ami_id: "{{ ec2_regions[ec2_region].amis['rhel7-tower'] }}"
    size: t2.medium
    os_type: linux
    disk_space: 20

  # Look at https://cloud-images.ubuntu.com/locator/ec2/ for Ubuntu AMIs
  ubuntu14:
    ami_id: "{{ ec2_regions[ec2_region].amis.ubuntu14 }}"
    size: t2.micro
    os_type: linux
    disk_space: 10

  ubuntu16:
    ami_id: "{{ ec2_regions[ec2_region].amis.ubuntu16 }}"
    size: t2.micro
    os_type: linux
    disk_space: 10

# Login names used for SSH connections. These are baked in to the AMIs.
ec2_login_names:
  rhel7-tower: ec2-user
  rhel7: ec2-user
  centos7-tower: centos
  centos7: centos
  ubuntu14: ubuntu
  ubuntu16: ubuntu


# Backwards compatability
types: "{{ ec2_lab_node_types }}"
aws_key_name: "{{ ec2_key_name }}"
