- name: Create EC2 security group
  ec2_group:
    name: insecure_all
    description: all ports open
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_exact_count >= 1
  tags:
    - always
    - provision

- name: Create or destroy EC2 instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_key_name }}"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_types[item.1.type].size }}"
    image: "{{ ec2_instance_types[item.1.type].ami_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ ec2_exact_count }}"
    count_tag:
      Name: "{{ ec2_name_prefix }}-{{ item.0.username }}-{{ item.1.name }}"
    instance_tags:
      Name: "{{ ec2_name_prefix }}-{{ item.0.username }}-{{ item.1.name }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id | default(omit) }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_instance_types[item.1.type].disk_space }}"
        delete_on_termination: true
  with_nested:
    - "{{ users }}"
    - "{{ ec2_lab_node_types }}"
  register: instances
  tags:
    - always
    - provision

- name: Include tasks only needed when creating instances
  include: create.yml
  static: no
  when: ec2_exact_count >= 1
  tags:
    - provision
